# Note that all secrets are stored on the CircleCI server. They will not appear in this file.

# Details when the `build` and `publish` steps will be run
workflows:
  version: 2
  main:
    jobs:
      # Always `build` any commits
      - build:
          filters:
            tags:
              only: /.*/
      # Only `publish` commits that have a git release label!
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

version: 2
jobs:
  # The `build` step that's referenced above
  build:
    docker:
      - image: cibuilds/chrome-extension:latest
    steps:
      - checkout
      - run:
          name: 'Install Dependencies'
          command: |
            apk update
            apk add tree
            apk add zip
            apk add nodejs-npm
            npm install
      - run:
          name: 'Create `build` Directory'
          command: mkdir ./build
      - run:
          name: 'Compile Templates'
          command: |
            echo "Compiling handlebars templates..."
            npm run compileTemplates
      - run:
          name: 'Make Extension Production Ready'
          command: |
            chmod +x ./.circleci/prod-ready.sh
            bash ./.circleci/prod-ready.sh
      - run:
          name: 'Debug: List All Files'
          command: tree -a -I 'node_modules|.git|.idea'
      - run:
          name: 'Debug: Print `manifest.json`'
          command: cat manifest.json
      - run:
          name: 'Check for Stale Data'
          command: node ./tools/expiredChecker.js
      - run:
          name: 'Package Extension'
          command: |
            zip -r ./build/extension.zip manifest.json src/ icon/
      # Use workspaces to move files between `build` and `publish`
      - persist_to_workspace:
          root: /root/project
          paths:
            - build
            - .circleci

  # The `published` step that's referenced above
  publish:
    docker:
      - image: cibuilds/chrome-extension:latest
    environment:
      # Not a secret :)
      - APP_ID: ndgeljpfnjlnmbgekhjkchhhgoiipnfi
    steps:
      - attach_workspace:
          at: /root/workspace
      - run:
          name: 'Publish to the Google Chrome Store'
          command: |
            set -eo pipefail
            chmod +x /root/workspace/.circleci/publish-extension.sh
            bash /root/workspace/.circleci/publish-extension.sh /root/workspace/build/extension.zip
